### ISSUE TITLE
Display list of matching steps

### ISSUE THREAD

**Issue by wallace** [tpope/vim-cucumber#21]
It would be great if matching step definitions were displayed and the option for jumping to the appropriate step definition were provided.

**Comment by ozzyaaron** [comment]
I think he may mean (and would be nice) something closer to autocompletion as I'm writing the step in the feature file. 

Quite often I'll write a feature using what I think are existing steps and then go through the definition files finding the real step definitions. It would be nice as you're typing to see the ones that match closely and then you would probably not have to go through the step of matching what you wrote to existing steps.
