### ISSUE TITLE
Feature: Jump back to feature file?

### ISSUE THREAD

**Issue by brycefisher** [tpope/vim-cucumber#40]
First off -- thank you 100000x! Jumping into a step definition is huge. I'd love to be able to jump back without resorting to a split screen (like I can with the tag stack). I tried all the commands listed in the README and none were quite what I was looking for. Thanks!

**Comment by tpope** [comment]
`CTRL-O`/`CTRL-^` are as close as you're going to get.

**Comment by brycefisher** [comment]
Thanks!
