### ISSUE TITLE
Changing the default indentation

### ISSUE THREAD

**Issue by jmoody** [tpope/vim-cucumber#45]
Apologies if this is the wrong place to ask a question.

I have been using the carlhuda/janus vim distribution for about 5 years. I use vim daily, but I have very little understand of how packages/plug-ins/customizations work.

Recently, janus switched to the vim-polyglot plug-in which includes this package.  Maybe janus always used this package?  I will admit that I don't really know.

What I do know is now vim is not indenting my cucumber features like it did before and this is really disruptive because I write a lot of cucumbers.

Is it possible to change the default indentation?  What I really want is to have _no_ indention at all. 

I have tried to disable the language support using the instructions on the vim-polyglot site, but without success.

I am also trying to get help from the carlhuda/janus community.

**Comment by tpope** [comment]
Vim ships with these same Cucumber runtime files, so I wouldn't expect vim-polyglot to change things much. You could `:setlocal indentexpr=0` to disable the indenting algorithm, perhaps from `after/indent/cucumber.vim`.
